/*
 * DIO_Cfg.c
 *
 * Created: 17-Jan-23 7:02:05 PM
 *  Author: NO3M4N
 */ 

#include "../../LIB/Std_types.h"

#include "DIO.h"
#include "DIO_Cfg.h"

const DIO_strPinCfg_t DIO_strPinCfg[32] =
{
	/*Pin Direction, INPUT CFG */
	/***PORT A ***/
	/*PIN 0*/	
	{
		.DIO_Pin_Direction = DIO_DIR_INPUT,
		.DIO_InputStatus = DIO_INPUT_PULL_UP
	},
	/*PIN 1*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 2*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 3*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 4*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 5*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 6*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 7*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},

	/***PORT B	 ***/

	/*PIN 8 B0*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 9 B1*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 10 B2*/ {DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 11 B3*/ {DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 12 B4*/ {DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 13 B5*/ {DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 14 B6*/ {DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 15 B7*/ {DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},	
	/***PORT c	 ***/

	/*PIN 16 C0*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 17 C1*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 18 C2*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 19 C3*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 20 C4*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 21 C5*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 22 C6*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 23 C7*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
												  
	/***PORT D	 ***/							  
												  
	/*PIN 24 D0*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_DOWN},
	/*PIN 25 D1*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_UP},
	/*PIN 26 D2*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_UP},
	/*PIN 27 D3*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_UP},
	/*PIN 28 D4*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_UP},
	/*PIN 29 D5*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_UP},
	/*PIN 30 D6*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_UP},
	/*PIN 31 D7*/	{DIO_DIR_OUTPUT,DIO_INPUT_PULL_UP}
	
};